variables:
  DOCKER_IMAGE_FULLNAME: $CI_REGISTRY/$CI_REGISTRY_IMAGE:$CI_COMMIT_SHA

stages:
  - check
  - build
  - deploy

.check-template:
  image: node:16
  before_script:
    - npm install -g pnpm@7
    - pnpm config set store-dir .pnpm-store
  cache:
    key:
      files:
        - pnpm-lock.yaml
    paths:
      - .pnpm-store

Lint:
  extends: .check-template
  stage: check
  script:
    - pnpm install
    - pnpm lint

Build:
  extends: .check-template
  stage: check
  script:
    - pnpm install
    - pnpm build
#
# .docker-template:
#   image: docker:latest
#   before_script:
#     - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
#
# Build and publish:
#   extends: .docker-template
#   stage: build
#   script:
#     - docker build --pull -t "$DOCKER_IMAGE_FULLNAME" .
#     - docker push "$DOCKER_IMAGE_FULLNAME"
#   only:
#     - main
#
# Deploy:
#   extends: .docker-template
#   stage: deploy
#   variables:
#     GIT_STRATEGY: none
#   image: docker-registry.esrf.fr/cs/ci-deploy
#   script:
#     - whdeploy "$CI_COMMIT_SHA"
#     - retag "$DOCKER_IMAGE_FULLNAME" "production"
#   environment:
#     name: production
#     url: https://myhdf5.hdfgroup.org/
#   only:
#     - main
